[package]
name = "greentea"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
ctrlc = "3.4.7"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.3", features = ["Win32_System_Power", "Win32_System_ProcessStatus"] }
